FROM python:3.13

WORKDIR /app

# Copiar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar todo el código
COPY . .

# Comando para ejecutar la app
CMD ["python", "app.py"]
